name: Automated Predictive Maintenance CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run linting
      - name: Lint Python code
        run: |
          echo "Running lint checks..."
          pip install flake8
          flake8 scripts/ --max-line-length=120

      # Step 5: Run unit tests
      #- name: Run unit tests
       # run: |
        #  echo "Running tests..."
          #pip install pytest
          #pytest tests/

      # Step 6: Debug data ingestion
      - name: Debug ingestion step
        run: |
          echo "Debugging data ingestion..."
          python scripts/ingestion.py || exit 1

      # Step 7: Run ETL process
      - name: Run ETL script
        run: |
          echo "Running ETL step..."
          python scripts/etl.py

      # Step 8: Train the model
      - name: Train model
        run: |
          echo "Training the model..."
          python scripts/train_script.py

      # Step 9: Perform additional training
      - name: Run additional training process
        run: |
          echo "Running training step..."
          python scripts/training.py

      # Step 10: Run inference and generate alerts
      - name: Run inference and alerts
        run: |
          echo "Running inference and generating alerts..."
          python scripts/inference.py

      # Step 11: Debug logs and outputs
      - name: Debug output files
        run: |
          echo "Debugging output files..."
          ls -lh /workspaces/Automated-Predictive-Maintenance/data
          ls -lh /workspaces/Automated-Predictive-Maintenance/models
          ls -lh /workspaces/Automated-Predictive-Maintenance/alerts

      # Step 12: Clean up generated files (Optional)
      - name: Clean up
        if: always()
        run: |
          echo "Cleaning up generated files..."
          rm -rf /workspaces/Automated-Predictive-Maintenance/models/*.json /workspaces/Automated-Predictive-Maintenance/alerts/alerts.txt
